### PR TITLE
Fix reentrancy bugs in subscribers

### LINKED ISSUE #208: Should change unfair lock to unfair recursive lock in Sink?
when AnyCancellable calls cancel function automatically in DEINIT, Sink's cancel function will be called, then terminateAndConsumeLock will be called. As the result, the receiveValue block and receiveCompletion block will be set to nil. Then objects in receiveValue block or receiveCompletion block may be destroyed. If there is an object that in block, it will call same sink's receive completion to finish in object's DEINIT function. That will make a crash cause call lock's lock function twice without unlock.

### PR DESCRIPTION
**Pull request by broadwaylamb**
Fixes #208.

### CODE REVIEW

File: Tests/OpenCombineTests/Helpers/AutomaticallyFinish.swift [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    }
+
+    func notify(_ value: Output) {
+        _ = publisher.send(value)
+    }
+
+    func listen(receiveCompletion: @escaping (Subscribers.Completion<Failure>) -> Void,
+                receiveValue: @escaping (Output) -> Void) -> AnyCancellable {
+        return publisher.sink(receiveCompletion: receiveCompletion,
+                            receiveValue: receiveValue)
```
Comment (OpenCombineBot) [inline Tests/OpenCombineTests/Helpers/AutomaticallyFinish.swift:35]: - :no_entry_sign: Function parameters should be aligned vertically if they're in multiple lines in a method call. (`vertical_parameter_alignment_on_call`)
